apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample
  labels:
    app: nginx-sample
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-sample
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      containers:
      - name: nginx
        image: quay.io/nghehg/simple-webapp
        env:
        - name: APP_COLOR
          value: "red"
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
